const images = [
    {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/01.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/02.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/03.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/04.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/05.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/06.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/07.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/08.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/09.jpg",
    },
    {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/10.jpg",
    },
    {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/11.jpg",
    },
    {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/12.jpg",
    },
    {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/13.jpg",
    },
    {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/14.jpg",
    },
    {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/15.jpg",
    },
    {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/05.jpg",
    },
    {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/04.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/05.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/06.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/07.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/08.jpg",
    },
    {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/05.jpg",
    },
    {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/04.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/05.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/06.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/07.jpg",
    },
     {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/08.jpg",
    },
    {
        image:"https://mobirise.com/extensions/consultingamp/assets/images/04.jpg",
    },


]